# To run: docker compose up

# docker compose version
version: "3"

# services to run, download if not available with "image: image-name"
services:
  my-api:
    build: . # build the my-api image if not available
    ports:
      - "8000:8000"

  web:
    image: nginx
    ports:
      - "80:80"

  db: # docker exec -it -u postgres <container-id> psql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

  cache: # docker exec -it <container-id> redis-cli
    image: redis
    ports:
      - "6379:6379"

  queue:
    image: rabbitmq
